### ISSUE TITLE
BulkExport APIs from Environment

### ISSUE THREAD

**Issue by ghost** [DinoChiesa/EdgeTools#2]
Hi Dino,

Regarding the bulkExportAPIs.js., i see it exports all the API proxies from the given organization. I have two or more environments in an organization. Is it possible to give environments option in the script?? Any advice or help would be greatful.

Regards,
Aravind

**Comment by mkaithakottil** [comment]
Hi i don't see the bulkexport.js file here...can you please add it?

**Comment by DinoChiesa** [comment]
This has been implemented in the latest release.  https://github.com/DinoChiesa/EdgeTools/blob/master/bulkExport/bulkExport.js
