### ISSUE TITLE
Please add bulkexport.js

### ISSUE THREAD

**Issue by dehu0815** [DinoChiesa/EdgeTools#6]
Hi,

can you please add the bulkexport.js in the repo? I only found the old and deleted bulkexportapi.js. Or did i miss something?

Thanks an lot.

Dennis

**Comment by grandDam** [comment]
Found here : https://github.com/DinoChiesa/apigee-edge-js-examples/blob/main/bulkExport.js

**Comment by dehu0815** [comment]
@grandDam perfect, thanks!
